version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the dist folder
      #- npm run-script build
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip index.js

  post_build:
    commands:
      - echo Build completed on `date`
      - echo updating lambda function...
      - aws lambda update-function-code --function-name WeatherHistory --zip-file fileb://deployment_package.zip
      - echo Done
# Include only the files required for your application to run.
artifacts:
  files:
      - '**/*'